# Generated by Django 4.2.2 on 2023-07-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='documents_file',
            field=models.FileField(default=1, upload_to='car/<django.db.models.fields.CharField>/document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='brand',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_type',
            field=models.CharField(choices=[('Euro-Track', 'Euro-Track'), ('Container', 'Container'), ('Tank', 'Tank'), ('Refrigerator', 'Refrigerator')], max_length=55),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='documents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='equipment',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarDocument',
        ),
        migrations.DeleteModel(
            name='CarEquipment',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
    ]
