# Generated by Django 4.2.2 on 2023-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carinfo_height_carinfo_length_carinfo_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
