# Generated by Django 4.2.2 on 2023-07-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='link',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
