# Generated by Django 4.2.2 on 2023-07-05 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydriverprofile',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_driver_profile', to='profiles.companyprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydriverprofile',
            name='mc_dot_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companydriverprofile',
            name='status',
            field=models.CharField(choices=[('free', 'free'), ('busy', 'busy')], default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('free', 'free'), ('busy', 'busy')], default=1, max_length=55),
            preserve_default=False,
        ),
    ]
