# Generated by Django 4.2.2 on 2023-07-05 05:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='company_user',
        ),
        migrations.AddField(
            model_name='companydriverprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_user',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
