# Generated by Django 4.2.2 on 2023-07-03 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_car', to='car.carinfo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=155, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('company_license', models.TextField(blank=True, null=True)),
                ('company_license_file', models.FileField(blank=True, null=True, upload_to='company license/license/<django.db.models.fields.CharField>/')),
                ('insurance_contract', models.TextField(blank=True, null=True)),
                ('insurance_contract_file', models.FileField(blank=True, null=True, upload_to='campany contract/contract/<django.db.models.fields.CharField>/')),
                ('billing_address', models.CharField(blank=True, max_length=155, null=True)),
                ('mc_dot_number', models.CharField(blank=True, max_length=10, null=True)),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_autopark', to='car.carinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
