# Generated by Django 4.2.2 on 2023-07-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('profiles', '0002_alter_baseprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_car', to='car.carinfo'),
        ),
    ]
