# Generated by Django 4.2.2 on 2023-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_is_company_dirver_companydriver_company_dirver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='is_company',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.BooleanField(default=True),
        ),
    ]
