# Generated by Django 4.2.2 on 2023-07-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_baseprofile_is_company_companyprofile_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseprofile',
            old_name='is_company',
            new_name='is_company_user',
        ),
    ]
