# Generated by Django 4.2.2 on 2023-07-04 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=200)),
                ('pickup_date', models.CharField(max_length=100)),
                ('delivery_date', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=200)),
                ('weight_of_goods', models.CharField(max_length=100)),
                ('type_of_goods', models.CharField(max_length=100)),
                ('required_equipment', models.CharField(max_length=200)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('driver_id', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('Looking for shipper', 'Looking for shipper'), ('Loading goods', 'Loading goods'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Looking for shipper', max_length=100)),
                ('activation_code', models.UUIDField(default=uuid.UUID('a6cd7d95-edcc-4eab-8bb7-e7a9a6297ca5'))),
                ('complete_code', models.UUIDField(default=uuid.UUID('1b1a21bc-d630-40f9-9b7b-44a3e04e11a8'))),
                ('cancel_code', models.UUIDField(default=uuid.UUID('e3c6c13e-02d4-47fb-90a5-fffd741f2fb3'))),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_confirm', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
