# Generated by Django 4.2.2 on 2023-07-01 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=200)),
                ('pickup_date', models.CharField(max_length=100)),
                ('delivery_date', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=200)),
                ('weight_of_goods', models.CharField(max_length=100)),
                ('type_of_goods', models.CharField(max_length=100)),
                ('required_equipment', models.CharField(max_length=200)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('activation_code', models.UUIDField(default=uuid.UUID('3c8be571-ca02-4c52-8948-3e35e61720f2'))),
                ('is_confirm', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
