# Generated by Django 4.2.2 on 2023-07-01 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('44edf6e0-3c3e-46d1-99b0-2085eab0a9fe')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('7f9c1a01-06e1-4db0-b158-f039ac49de7c')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('c4643d03-8d9b-4af2-b9e7-a60f8cf255cc')),
        ),
    ]
