# Generated by Django 4.2.2 on 2023-07-03 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('9cb15732-c55c-4ea3-a367-f75149f1db3f')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('4a70f75b-6a36-44ed-80b2-76d2b2022e16')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('3232e0a4-4027-4ca1-9122-b902aa536959')),
        ),
    ]
