# Generated by Django 4.2.2 on 2023-07-01 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('b5302c67-c28a-4ecc-9ace-6e55aa68c7e7')),
        ),
    ]
