# Generated by Django 4.2.2 on 2023-07-03 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='driver_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('1b34f66b-6801-42fb-bb62-e527545c2905')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('b98b4895-7454-4e43-93fd-004a23dd0003')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('d1b10e74-12ce-4b7b-8302-01c52924383a')),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Looking for shipper', 'Looking for shipper'), ('Loading goods', 'Loading goods'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Looking for shipper', max_length=100),
        ),
    ]
