# Generated by Django 4.2.2 on 2023-07-04 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('6eaaf4d4-40a5-45b9-9ddb-9ddaf81c8ad1')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('7f675e79-8738-497b-b07c-a8afb4ff7907')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('6f1c440d-a708-429b-a9e2-aa793655ff7f')),
        ),
    ]
