# Generated by Django 4.2.2 on 2023-07-04 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('d0c41aa8-5dac-4caf-952e-9b3144a980cb')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('def48f5a-3520-4b73-b06e-a81a0265c119')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('c6bdb2f0-9f04-4402-9834-ff047478ccc9')),
        ),
    ]
