# Generated by Django 4.2.2 on 2023-07-05 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('da4647bc-67a4-42b5-8c6f-04d78d19496e')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('dfe7e557-f909-4eb6-a270-cc025a6018d6')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('2717c621-98fb-4b44-995b-f36731274e40')),
        ),
    ]
