# Generated by Django 4.2.2 on 2023-07-01 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='cancel_requested_at',
            new_name='started_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('2c07cbc5-d3ed-4d9e-9a0f-a3e357f52ac9')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('5ee3741c-bd60-4331-934a-4bb3c1c42deb')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('cfbbc437-74ec-4258-8ab7-3342921705d2')),
        ),
    ]
