# Generated by Django 4.2.2 on 2023-07-05 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_cost_alter_job_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('df7b9952-d69f-437b-b5b0-9d3be1de5498')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('7ea49db8-59c9-4be2-822f-7c61973a7227')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('e7509f84-0dc3-41d4-949b-5dbe1eb13e80')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.CharField(default=3700, max_length=20),
        ),
    ]
