# Generated by Django 4.2.2 on 2023-07-05 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('38dd2457-ccf1-4de8-a0c0-8897665327d7')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('9e5c55ed-0d90-47ad-b585-5e60d51d12c8')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('11f85c79-5c18-4156-ad8a-d8d7e69078bf')),
        ),
    ]
