# Generated by Django 4.2.2 on 2023-07-05 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('ab3c962c-42d2-4f42-ba88-1c7d1f33d3c9')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('7f9d0644-806f-49ee-a81a-7fcdd60b1797')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('82f8b688-1c92-48d9-b333-73379e040c49')),
        ),
    ]
