# Generated by Django 4.2.2 on 2023-07-01 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('0a0b423c-acd9-43e6-ac8d-0240ab88d870')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('b963711d-0a76-465c-a908-fc48ca030484')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('fd2901d7-8161-4cf3-ac9e-d696d42fb051')),
        ),
    ]
