# Generated by Django 4.2.2 on 2023-07-03 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('1a3d98f4-fb1c-45da-9b71-b07abe2971a7')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('453b64ba-cf56-45aa-a03e-e8f5cdb81fd3')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('65ea7ea2-3fd0-40d9-baca-e430a91ebcc9')),
        ),
    ]
