# Generated by Django 4.2.2 on 2023-07-03 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('12343d0e-1b16-44bd-a298-dd64e7b066f3')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('da954d98-5062-409a-ad26-e66bce82d287')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('c7e66a09-447f-43c8-91c8-50a3fe188691')),
        ),
    ]
