# Generated by Django 4.2.2 on 2023-07-05 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('c5572ad1-3a8e-4896-bd21-5786622fce90')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('f9c4cb5d-6fcf-4dfc-8572-66300158b1ad')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('90644d7d-c19d-4296-b3d5-49fd2e450c00')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.CharField(default=2480, max_length=20),
        ),
    ]
