# Generated by Django 4.2.2 on 2023-07-01 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('35cbad86-7fab-417c-ae16-7dec4585e3a5')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('15a6d3af-e5b0-44bf-9763-b4fe99b6bfe8')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('b636ff8a-a1b2-42cf-ab6e-b1936ccd7c78')),
        ),
    ]
