# Generated by Django 4.2.2 on 2023-07-05 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('6d559f91-cd89-4595-ade1-ce7c792691d5')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('e9f5919f-059b-40f7-ba8c-e69a40a703be')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('93f7b7ea-4bfb-4b70-aef4-11781da81ff8')),
        ),
    ]
