# Generated by Django 4.2.2 on 2023-07-05 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('09f18b3f-39f3-40ba-8a83-da147d899007')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('51480089-7bdb-4ee2-95d8-444e072a489e')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('72633128-0bb6-4462-aec1-3e3a381c3c7c')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.CharField(default=3781, max_length=20),
        ),
    ]
