# Generated by Django 4.2.2 on 2023-07-01 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('4175b688-d8d4-4357-a219-2c36d3bf5c83')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('6d432c7f-5bea-4057-acfc-fa1c5dfa7cf9')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('dff147c2-0f43-4ccf-a801-773eae31c83c')),
        ),
    ]
