# Generated by Django 4.2.2 on 2023-07-05 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('34d65bb2-0445-493d-8a63-9f949738558e')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('521ea370-a241-4f49-bc81-011ff3ce3aa7')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('767f386b-f35d-4caf-bb45-abc208a3dcbf')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.CharField(default=1433, max_length=20),
        ),
    ]
