# Generated by Django 4.2.2 on 2023-07-03 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('7ccbe019-4a10-4a71-81ed-7ca796426075')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('39d71889-07f7-4767-a77b-08fcb24afbeb')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('0d2f009a-eb24-45e2-aacb-2d0607b63aa9')),
        ),
    ]
