# Generated by Django 4.2.2 on 2023-07-02 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('58ce2dcc-5259-4714-aa3e-e7783057c35a')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('c84b6430-af39-4f9b-b613-ed6ff97d432e')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('39c3c5ee-cd25-4c59-a6b9-af0e2c9f9407')),
        ),
    ]
