# Generated by Django 4.2.2 on 2023-07-05 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('7fe3fbe8-8109-41f8-a2eb-e429edfcfd5f')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('35ff989f-2907-4682-a73d-13ef1eb35ca8')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('905d71df-e770-41fd-b5dc-e2110dbe6700')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.CharField(default=1256, max_length=20),
        ),
    ]
