# Generated by Django 4.2.2 on 2023-07-05 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_activation_code_alter_job_cancel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('a3203d75-ac69-4f58-a81b-73a220809ea3')),
        ),
        migrations.AlterField(
            model_name='job',
            name='cancel_code',
            field=models.UUIDField(default=uuid.UUID('44cc3c6b-ceed-4226-abcf-4e6b6e97a062')),
        ),
        migrations.AlterField(
            model_name='job',
            name='complete_code',
            field=models.UUIDField(default=uuid.UUID('0b7eec65-0103-4da3-b156-03a4a93bca3c')),
        ),
    ]
