# Generated by Django 4.2.2 on 2023-07-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='email',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
