# Generated by Django 4.2.2 on 2023-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_recovery_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
