# Generated by Django 4.2.2 on 2023-06-29 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_recovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_recovery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='recovery_code',
            field=models.CharField(max_length=8),
        ),
    ]
