# Generated by Django 4.2.2 on 2023-06-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_recovery_email_alter_recovery_recovery_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='password_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
