# Generated by Django 4.2.2 on 2023-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_phone_alter_customuser_mc_dot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mc_dot_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
